version: '3'
services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    restart: always
    networks:
      - mongo

  rhythm:
    image: ubeydekara/rhythm:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mongo
    depends_on:
      - mongodb

networks:
  mongo:
    driver: bridge