version: '3'
services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    restart: always
    networks:
      - mongo

  rhythm:
    image: ubeydekara/rhythm:0.0.3-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      YOUTUBE_APIKEY: ${YOUTUBE_APIKEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    networks:
      - mongo
    depends_on:
      - mongodb

networks:
  mongo:
    driver: bridge