spring:
  application:
    name: music-service

  data:
    mongodb:
      uri: mongodb://root:12345@localhost:27017/rhythm?authSource=admin

rest:
  timeout: 30000

client:
  youtube:
    apikey: ${YOUTUBE_APIKEY}
  spotify:
    clientId: ${SPOTIFY_CLIENT_ID}
    clientSecret: ${SPOTIFY_CLIENT_SECRET}